# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmodels', '0003_nestedcontentobject_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentobject',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
