# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmodels', '0004_contentobject_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestedcontentobject',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
